### ISSUE TITLE
Mismatch between client and server encodings?

### ISSUE THREAD

**Issue by kcoop** [Gurpartap/aescrypt#1]
Great idea for a pair of modules, thanks.

In my use case, I'm encoding a message in iOS, sending the encoded version to rails, and then in rails encoding the same message and seeing if the two agree. And oddly, they don't, by three spaces. 

Here is the iOS code:

```
    NSString *text = @"8954302B-3291-42D8-A52F-EF1023F78AA3d115f8c31c33a6a70f60fe0ec0830fac2012-08-19T05:04:01Z";
    NSString *sharedSecret = @"ef7468fe8e05ad22fa0d4a5554205b65";
    NSString *signature = [AESCrypt encrypt:text password:sharedSecret];
    NSLog(@"Signature: %@", signature);

    // Outputs: Signature: I1rougkuUGC/9Tu+uv7e8vpT975ca6rCZueCQTe3pq0aY6XtBcre1Qd6AokZ3d0NAZPqxxGYwPe5aXQHy4Cef4m59fVgglYawKnRwA5e3ZhouQrcWUBixjyU4rUk8/yP
```

Here is the Rails code:

```
text = "8954302B-3291-42D8-A52F-EF1023F78AA3d115f8c31c33a6a70f60fe0ec0830fac2012-08-19T05:04:01Z";
shared_secret = "ef7468fe8e05ad22fa0d4a5554205b65"
reference_signature = AESCrypt.encrypt(text, shared_secret)

reference_signature in debugger is: "I1rougkuUGC/9Tu+uv7e8vpT975ca6rCZueCQTe3pq0aY6XtBcre1Qd6AokZ 3d0NAZPqxxGYwPe5aXQHy4Cef4m59fVgglYawKnRwA5e3ZhouQrcWUBixjyU 4rUk8/yP "
```

Note the spaces in reference_signature: between the Z and 3, the U and the 4, and at the end of the string.

This is rails Rails 3.2.3, ruby 1.9.3p194, iOS 5.1.

**Comment by kcoop** [comment]
Sorry, those weren't spaces, they were linefeeds.

**Comment by Gurpartap** [comment]
Likely that both the outputs had linefeeds. One of them presented them with spaces for formatting, I believe.
